// Generated from the guild's "Blacksmith Recipies" doc — a one-time extraction,
// not a live feed, so edits to the doc need a re-run of scripts/gen_recipes.py.
//
// Recipes are grouped by the station that crafts them. Part II of the doc lists
// only what the Blacksmith Forge adds; it also carries most Skyforge recipes
// with the same ingredients, which is why the two lists differ in size rather
// than one containing the other.

export interface RecipeIngredient {
  qty: number;
  item: string;
}

export interface Recipe {
  /** The crafting station this was recorded at. */
  station: string;
  category: string;
  name: string;
  /** Armour rating, or damage for weapons. 0 where the item has neither. */
  stat: number;
  ingredients: RecipeIngredient[];
}

export const RECIPE_NOTES: string[] = [
  "Blacksmith Forge: New recipes only (152). The Blacksmith Forge also carries most Part I recipes with identical ingredients.",
  "Smelter: Ore-to-ingot conversions. Fuel tiers: Poor Charcoal (iron/corundum), Charcoal (gold/silver/steel), Charcoal Briquette (orichalcum/moonstone), Coke (ebony/quicksilver/malachite). Dwemer scrap pieces melt into multiple Dwarven Metal Ingots each (3–5 depending on the piece).",
  "Item stats reflect the modded values shown in-game. All previously uncertain ingredient counts have been verified against clearer footage."
];

export const RECIPES: Recipe[] = [
  { station: "Skyforge", category: "Jewelry", name: "Jade and Sapphire Circlet", stat: 0, ingredients: [{ qty: 1, item: "Refined Malachite" }, { qty: 1, item: "Sapphire" }] },
  { station: "Skyforge", category: "Jewelry", name: "Silver Amethyst Ring", stat: 0, ingredients: [{ qty: 1, item: "Amethyst" }, { qty: 1, item: "Silver Ingot" }] },
  { station: "Skyforge", category: "Jewelry", name: "Silver and Moonstone Circlet", stat: 0, ingredients: [{ qty: 2, item: "Silver Ingot" }, { qty: 1, item: "Refined Moonstone" }] },
  { station: "Skyforge", category: "Jewelry", name: "Silver and Sapphire Circlet", stat: 0, ingredients: [{ qty: 2, item: "Silver Ingot" }, { qty: 1, item: "Sapphire" }] },
  { station: "Skyforge", category: "Jewelry", name: "Silver Emerald Necklace", stat: 0, ingredients: [{ qty: 1, item: "Flawless Emerald" }, { qty: 1, item: "Silver Ingot" }] },
  { station: "Skyforge", category: "Jewelry", name: "Silver Garnet Ring", stat: 0, ingredients: [{ qty: 1, item: "Garnet" }, { qty: 1, item: "Silver Ingot" }] },
  { station: "Skyforge", category: "Jewelry", name: "Silver Jeweled Necklace", stat: 0, ingredients: [{ qty: 2, item: "Flawless Garnet" }, { qty: 1, item: "Silver Ingot" }] },
  { station: "Skyforge", category: "Jewelry", name: "Silver Necklace", stat: 0, ingredients: [{ qty: 1, item: "Silver Ingot" }] },
  { station: "Skyforge", category: "Jewelry", name: "Silver Ring", stat: 0, ingredients: [{ qty: 1, item: "Silver Ingot" }] },
  { station: "Skyforge", category: "Jewelry", name: "Silver Ruby Ring", stat: 0, ingredients: [{ qty: 1, item: "Ruby" }, { qty: 1, item: "Silver Ingot" }] },
  { station: "Skyforge", category: "Jewelry", name: "Silver Sapphire Necklace", stat: 0, ingredients: [{ qty: 1, item: "Silver Ingot" }, { qty: 1, item: "Flawless Sapphire" }] },
  { station: "Skyforge", category: "Light Armor", name: "Large Fur Collar", stat: 0, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Leather Armor", stat: 29, ingredients: [{ qty: 4, item: "Leather" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Light Armor", name: "Leather Boots", stat: 8, ingredients: [{ qty: 2, item: "Leather" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Light Armor", name: "Leather Helmet", stat: 13, ingredients: [{ qty: 2, item: "Leather" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Light Armor", name: "Mail and Jacket", stat: 36, ingredients: [{ qty: 1, item: "Linen Wrap" }, { qty: 4, item: "Leather Strips" }, { qty: 2, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Light Armor", name: "Northern Fur Boots", stat: 7, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Northern Fur Gloves", stat: 7, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Northern Fur Hat", stat: 12, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Northern Fur Shield", stat: 17, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Northern Hide Armor", stat: 22, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Northern Hide Boots", stat: 6, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Northern Hide Gauntlets", stat: 6, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Northern Hide Helmet", stat: 11, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Northern Leather Armor", stat: 29, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Northern Studded Armor", stat: 25, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Oiled Mail and Hide Armor", stat: 35, ingredients: [{ qty: 1, item: "Hide Armor" }, { qty: 4, item: "Leather Strips" }, { qty: 2, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Light Armor", name: "Oiled Mail and Jacket", stat: 38, ingredients: [{ qty: 1, item: "Linen Wrap" }, { qty: 4, item: "Leather Strips" }, { qty: 2, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Light Armor", name: "Oiled Mail Hauberk", stat: 30, ingredients: [{ qty: 1, item: "Linen Wrap" }, { qty: 4, item: "Leather Strips" }, { qty: 2, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Light Armor", name: "Rogue's Hide Armor", stat: 22, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Rogue's Hide Gloves", stat: 6, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Rogue's Hood", stat: 11, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Rogue's Hood, Lowered", stat: 11, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Rugged Leather Armor", stat: 29, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Rugged Leather Boots", stat: 8, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Rugged Leather Gauntlets", stat: 8, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Rugged Leather Helmet", stat: 13, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Rugged Leather Shield", stat: 17, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Studded Armor", stat: 25, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Light Armor", name: "Stormcloak Braided Armor", stat: 25, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Stormcloak Conical Helmet", stat: 12, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Stormcloak Hide Armor", stat: 25, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Stormcloak Hide Gauntlets", stat: 7, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Stormcloak Hide Helmet", stat: 12, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Stormcloak Leather Helmet", stat: 12, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Stormcloak Light Shield", stat: 21, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Light Armor", name: "Stormcloak Soldier Boots", stat: 7, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Stormcloak Soldier Gauntlets", stat: 7, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Light Armor", name: "Stormcloak Soldier Helmet", stat: 12, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Northern Iron Armor", stat: 27, ingredients: [{ qty: 5, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Northern Iron Boots", stat: 11, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Northern Iron Gauntlets", stat: 11, ingredients: [{ qty: 2, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Northern Iron Helmet", stat: 16, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Northern Steel Armor", stat: 33, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 4, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Northern Steel Gauntlets", stat: 13, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Northern Steel Helmet", stat: 19, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Rugged Iron Armor", stat: 27, ingredients: [{ qty: 5, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Rugged Iron Boots", stat: 11, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Rugged Iron Gauntlets", stat: 11, ingredients: [{ qty: 2, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Rugged Iron Helmet", stat: 16, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Rugged Steel Boots", stat: 13, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 3, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Rugged Steel Gauntlets", stat: 13, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Rugged Steel Shield", stat: 26, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 3, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Runic Iron Boots", stat: 11, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Runic Iron Gauntlets", stat: 11, ingredients: [{ qty: 2, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Runic Iron Helmet", stat: 16, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Steel Armor", stat: 33, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 4, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Steel Cuffed Boots", stat: 13, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 3, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Steel Helmet", stat: 19, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Steel Ingot" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Steel Horned Helmet", stat: 19, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Steel Ingot" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Steel Imperial Gauntlets", stat: 13, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Steel Ingot" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Steel Nordic Gauntlets", stat: 13, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Steel Shield", stat: 26, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 3, item: "Steel Ingot" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Steel Shin Boots", stat: 13, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }, { qty: 3, item: "Steel Ingot" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Chainmail Armor", stat: 27, ingredients: [{ qty: 4, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Heavy Iron Helmet", stat: 16, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Heavy Lamellar Armor", stat: 27, ingredients: [{ qty: 4, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Heavy Lamellar Boots", stat: 11, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Heavy Lamellar Gauntlets", stat: 11, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Heavy Soldier Boots", stat: 11, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Heavy Soldier Gauntlets", stat: 11, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Heavy Soldier Helmet", stat: 16, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Iron Helmet", stat: 16, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Lamellar Armor", stat: 27, ingredients: [{ qty: 4, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Lamellar Boots", stat: 11, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Stormcloak Shield", stat: 22, ingredients: [{ qty: 4, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Wrought Iron Boots", stat: 11, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Wrought Iron Gauntlets", stat: 11, ingredients: [{ qty: 2, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Heavy Armor", name: "Wrought Iron Helmet", stat: 16, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Long Bow", stat: 6, ingredients: [{ qty: 8, item: "Firewood" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Northern Iron Battleaxe", stat: 18, ingredients: [{ qty: 4, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Northern Iron Greatsword", stat: 17, ingredients: [{ qty: 4, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Northern Iron Mace", stat: 10, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Northern Iron War Axe", stat: 9, ingredients: [{ qty: 2, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Northern Iron Warhammer", stat: 20, ingredients: [{ qty: 4, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Steel Arrow", stat: 10, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 1, item: "Firewood" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Steel Battleaxe", stat: 20, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 4, item: "Steel Ingot" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Steel Dagger", stat: 6, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Steel Greatsword", stat: 19, ingredients: [{ qty: 2, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 4, item: "Steel Ingot" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Steel Sword", stat: 9, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 2, item: "Steel Ingot" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Steel War Axe", stat: 10, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Skyforge", category: "Weapons & Ammo", name: "Steel Warhammer", stat: 23, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 4, item: "Steel Ingot" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Copper and Moonstone Circlet", stat: 0, ingredients: [{ qty: 1, item: "Corundum Ingot" }, { qty: 1, item: "Refined Moonstone" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Copper and Onyx Circlet", stat: 0, ingredients: [{ qty: 1, item: "Corundum Ingot" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Copper and Ruby Circlet", stat: 0, ingredients: [{ qty: 1, item: "Corundum Ingot" }, { qty: 1, item: "Ruby" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Copper and Sapphire Circlet", stat: 0, ingredients: [{ qty: 1, item: "Corundum Ingot" }, { qty: 1, item: "Sapphire" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Gold and Emerald Circlet", stat: 0, ingredients: [{ qty: 2, item: "Gold Ingot" }, { qty: 1, item: "Emerald" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Gold and Ruby Circlet", stat: 0, ingredients: [{ qty: 2, item: "Gold Ingot" }, { qty: 1, item: "Ruby" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Gold Diamond Necklace", stat: 0, ingredients: [{ qty: 1, item: "Flawless Diamond" }, { qty: 1, item: "Gold Ingot" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Gold Diamond Ring", stat: 0, ingredients: [{ qty: 1, item: "Diamond" }, { qty: 1, item: "Gold Ingot" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Gold Emerald Ring", stat: 0, ingredients: [{ qty: 1, item: "Emerald" }, { qty: 1, item: "Gold Ingot" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Gold Necklace", stat: 0, ingredients: [{ qty: 1, item: "Gold Ingot" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Gold Ring", stat: 0, ingredients: [{ qty: 1, item: "Gold Ingot" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Gold Ruby Necklace", stat: 0, ingredients: [{ qty: 1, item: "Flawless Ruby" }, { qty: 1, item: "Gold Ingot" }] },
  { station: "Blacksmith Forge", category: "Jewelry", name: "Jade and Emerald Circlet", stat: 0, ingredients: [{ qty: 1, item: "Refined Malachite" }, { qty: 1, item: "Emerald" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Armor", stat: 32, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 4, item: "Refined Moonstone" }, { qty: 3, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Boots", stat: 9, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Refined Moonstone" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Cape", stat: 0, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Gloves", stat: 9, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Refined Moonstone" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Hood", stat: 15, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Refined Moonstone" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Mask", stat: 0, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Plate Armor", stat: 37, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 4, item: "Refined Moonstone" }, { qty: 3, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Plate Boots", stat: 14, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 2, item: "Refined Moonstone" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Plate Gauntlets", stat: 14, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 1, item: "Refined Moonstone" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Plate Helmet", stat: 20, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 2, item: "Refined Moonstone" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Bosmer Shoulder Cape", stat: 0, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Common Aketon", stat: 25, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Common Boots", stat: 7, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Common Brigandine", stat: 25, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Common Gambeson", stat: 25, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Common Gauntlets", stat: 7, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Common Gloves", stat: 7, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Common Lamellar Armor", stat: 26, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Common Lamellar Tunic", stat: 26, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Common Padded Tunic", stat: 26, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Elven Armor", stat: 29, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 1, item: "Leather" }, { qty: 4, item: "Refined Moonstone" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Elven Boots", stat: 9, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }, { qty: 2, item: "Refined Moonstone" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Elven Gauntlets", stat: 9, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }, { qty: 1, item: "Refined Moonstone" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Elven Gilded Armor", stat: 38, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Refined Moonstone" }, { qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Quicksilver Ingot" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Elven Helmet", stat: 15, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 1, item: "Leather" }, { qty: 2, item: "Refined Moonstone" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Elven Shield", stat: 23, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 4, item: "Refined Moonstone" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Fur Bracers", stat: 7, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Fur Coat", stat: 25, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 5, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Fur Collar", stat: 0, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Fur Hat", stat: 12, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Fur Shawl", stat: 25, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 6, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Fur Shoes", stat: 7, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Fur Skirt", stat: 25, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 5, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Hide Armor", stat: 22, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Hide Boots", stat: 6, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Hide Bracers", stat: 6, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Hide Helmet", stat: 11, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Hide Shield", stat: 17, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Hunter's Fur Boots", stat: 7, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Hunter's Fur Coat", stat: 25, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Hunter's Fur Gloves", stat: 7, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Hunter's Fur Shield", stat: 17, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Leather Bracers", stat: 8, ingredients: [{ qty: 1, item: "Leather" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Mail and Hide Armor", stat: 33, ingredients: [{ qty: 1, item: "Hide Armor" }, { qty: 4, item: "Leather Strips" }, { qty: 2, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Mail and Surcoat", stat: 25, ingredients: [{ qty: 1, item: "Linen Wrap" }, { qty: 4, item: "Leather Strips" }, { qty: 2, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Mail Tunic", stat: 28, ingredients: [{ qty: 1, item: "Linen Wrap" }, { qty: 4, item: "Leather Strips" }, { qty: 2, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Orcish Hide Armor", stat: 29, ingredients: [{ qty: 1, item: "Orichalcum Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Orcish Hide Boots", stat: 8, ingredients: [{ qty: 1, item: "Orichalcum Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Orcish Hide Gauntlets", stat: 8, ingredients: [{ qty: 1, item: "Orichalcum Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Orcish Hide Helmet", stat: 13, ingredients: [{ qty: 1, item: "Orichalcum Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Orcish Studded Armor", stat: 32, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Orichalcum Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 4, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Light Armor", name: "Rogue's Hide Boots", stat: 6, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Banded Iron Armor", stat: 30, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 5, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Banded Iron Shield", stat: 24, ingredients: [{ qty: 1, item: "Leather Strips" }, { qty: 4, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Banded Northern Iron Armor", stat: 30, ingredients: [{ qty: 5, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Banded Northern Iron Shield", stat: 24, ingredients: [{ qty: 4, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Banded Rugged Iron Armor", stat: 30, ingredients: [{ qty: 5, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Banded Rugged Iron Shield", stat: 24, ingredients: [{ qty: 4, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Banded Runic Iron Armor", stat: 30, ingredients: [{ qty: 5, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Banded Wrought Iron Armor", stat: 30, ingredients: [{ qty: 5, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Common Chain Mail", stat: 27, ingredients: [{ qty: 5, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Common Mail Tunic", stat: 27, ingredients: [{ qty: 5, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Dwarven Armor", stat: 37, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 3, item: "Dwarven Metal Ingot" }, { qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Steel Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Dwarven Boots", stat: 14, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Dwarven Metal Ingot" }, { qty: 1, item: "Steel Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Dwarven Gauntlets", stat: 14, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Dwarven Metal Ingot" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Dwarven Helmet", stat: 20, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 2, item: "Dwarven Metal Ingot" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Dwarven Shield", stat: 28, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 2, item: "Dwarven Metal Ingot" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Imperial Battlemage Robes", stat: 27, ingredients: [{ qty: 4, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 2, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Iron Armor", stat: 27, ingredients: [{ qty: 5, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Iron Boots", stat: 11, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 3, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Iron Gauntlets", stat: 11, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Iron Helmet", stat: 16, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 3, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Jerall Dwarven Armor", stat: 37, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 3, item: "Dwarven Metal Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Jerall Dwarven Boots", stat: 14, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 2, item: "Dwarven Metal Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Jerall Dwarven Gauntlets", stat: 14, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Dwarven Metal Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Northern Iron Shield", stat: 22, ingredients: [{ qty: 4, item: "Iron Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Orcish Armor", stat: 43, ingredients: [{ qty: 3, item: "Leather Strips" }, { qty: 4, item: "Orichalcum Ingot" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Orcish Boots", stat: 16, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }, { qty: 3, item: "Orichalcum Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Orcish Gauntlets", stat: 16, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Orichalcum Ingot" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Orcish Helmet", stat: 22, ingredients: [{ qty: 2, item: "Leather Strips" }, { qty: 2, item: "Orichalcum Ingot" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Orcish Shield", stat: 32, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 4, item: "Orichalcum Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Velothi Dwarven Armor", stat: 37, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 3, item: "Dwarven Metal Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Velothi Dwarven Helmet", stat: 20, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Steel Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 2, item: "Dwarven Metal Ingot" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Wrought Iron Armor", stat: 27, ingredients: [{ qty: 5, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Heavy Armor", name: "Wrought Iron Shield", stat: 22, ingredients: [{ qty: 4, item: "Iron Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Bosmer Blade", stat: 9, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Refined Moonstone" }, { qty: 1, item: "Quicksilver Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Bosmer Bow", stat: 14, ingredients: [{ qty: 2, item: "Refined Moonstone" }, { qty: 1, item: "Quicksilver Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Common Arming Sword", stat: 9, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Common Battleaxe", stat: 20, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Common Bearded Axe", stat: 10, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Common Bow", stat: 10, ingredients: [{ qty: 3, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Common Broadaxe", stat: 20, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Common Dagger", stat: 6, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Common Hafted Axe", stat: 20, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Common Hand Axe", stat: 10, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Common Sword", stat: 9, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Common War Axe", stat: 10, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Dwarven Arrow", stat: 14, ingredients: [{ qty: 1, item: "Firewood" }, { qty: 1, item: "Dwarven Metal Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Dwarven Battleaxe", stat: 23, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 2, item: "Dwarven Metal Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Dwarven Bow", stat: 13, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Dwarven Metal Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Dwarven Dagger", stat: 8, ingredients: [{ qty: 1, item: "Dwarven Metal Ingot" }, { qty: 1, item: "Steel Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Dwarven Greatsword", stat: 21, ingredients: [{ qty: 2, item: "Dwarven Metal Ingot" }, { qty: 2, item: "Steel Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 2, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Dwarven Sword", stat: 11, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 1, item: "Dwarven Metal Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Dwarven War Axe", stat: 12, ingredients: [{ qty: 1, item: "Steel Ingot" }, { qty: 1, item: "Dwarven Metal Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Dwarven Warhammer", stat: 25, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 1, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 2, item: "Dwarven Metal Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Elven Arrow", stat: 16, ingredients: [{ qty: 1, item: "Refined Moonstone" }, { qty: 1, item: "Firewood" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Elven Battleaxe", stat: 24, ingredients: [{ qty: 2, item: "Iron Ingot" }, { qty: 1, item: "Quicksilver Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 2, item: "Refined Moonstone" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Elven Bow", stat: 14, ingredients: [{ qty: 1, item: "Quicksilver Ingot" }, { qty: 2, item: "Refined Moonstone" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Elven Dagger", stat: 9, ingredients: [{ qty: 1, item: "Refined Moonstone" }, { qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Quicksilver Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Elven Greatsword", stat: 23, ingredients: [{ qty: 2, item: "Refined Moonstone" }, { qty: 2, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 1, item: "Quicksilver Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Elven Mace", stat: 14, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Refined Moonstone" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Quicksilver Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Elven Sword", stat: 12, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Refined Moonstone" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Quicksilver Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Elven War Axe", stat: 13, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Refined Moonstone" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Quicksilver Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Elven Warhammer", stat: 26, ingredients: [{ qty: 2, item: "Iron Ingot" }, { qty: 1, item: "Quicksilver Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 2, item: "Refined Moonstone" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Hunting Bow", stat: 8, ingredients: [{ qty: 2, item: "Steel Ingot" }, { qty: 8, item: "Firewood" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Leather" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Iron Battleaxe", stat: 18, ingredients: [{ qty: 4, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Iron Dagger", stat: 4, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Iron Greatsword", stat: 17, ingredients: [{ qty: 4, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Iron Mace", stat: 10, ingredients: [{ qty: 3, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Iron War Axe", stat: 9, ingredients: [{ qty: 2, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Iron Warhammer", stat: 20, ingredients: [{ qty: 4, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Northern Iron Dagger", stat: 4, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Orcish Arrow", stat: 12, ingredients: [{ qty: 1, item: "Orichalcum Ingot" }, { qty: 1, item: "Firewood" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Orcish Battleaxe", stat: 21, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 4, item: "Orichalcum Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Orcish Bow", stat: 11, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 2, item: "Orichalcum Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Orcish Dagger", stat: 7, ingredients: [{ qty: 1, item: "Orichalcum Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Orcish Greatsword", stat: 20, ingredients: [{ qty: 4, item: "Orichalcum Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 2, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Orcish Mace", stat: 12, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 3, item: "Orichalcum Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Orcish Sword", stat: 10, ingredients: [{ qty: 2, item: "Orichalcum Ingot" }, { qty: 1, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Orcish War Axe", stat: 11, ingredients: [{ qty: 2, item: "Orichalcum Ingot" }, { qty: 2, item: "Leather Strips" }, { qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Weapons & Ammo", name: "Orcish Warhammer", stat: 24, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 3, item: "Leather Strips" }, { qty: 4, item: "Orichalcum Ingot" }] },
  { station: "Blacksmith Forge", category: "Tools & Miscellaneous", name: "Hinge", stat: 0, ingredients: [{ qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Tools & Miscellaneous", name: "House Key", stat: 0, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }, { qty: 1, item: "Leather Strips" }] },
  { station: "Blacksmith Forge", category: "Tools & Miscellaneous", name: "Iron Fittings", stat: 0, ingredients: [{ qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Tools & Miscellaneous", name: "Lockpick", stat: 0, ingredients: [{ qty: 1, item: "Iron Ingot" }, { qty: 1, item: "Corundum Ingot" }] },
  { station: "Blacksmith Forge", category: "Tools & Miscellaneous", name: "Nails", stat: 0, ingredients: [{ qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Tools & Miscellaneous", name: "Pickaxe", stat: 6, ingredients: [{ qty: 1, item: "Iron Ingot" }] },
  { station: "Blacksmith Forge", category: "Tools & Miscellaneous", name: "Woodcutter's Axe", stat: 6, ingredients: [{ qty: 1, item: "Iron Ingot" }] },
  { station: "Smelter", category: "Ingots & Refined Materials", name: "Corundum Ingot", stat: 0, ingredients: [{ qty: 8, item: "Corundum Ore" }, { qty: 8, item: "Poor Charcoal" }] },
  { station: "Smelter", category: "Ingots & Refined Materials", name: "Ebony Ingot", stat: 0, ingredients: [{ qty: 2, item: "Ebony Ore" }, { qty: 2, item: "Coke" }] },
  { station: "Smelter", category: "Ingots & Refined Materials", name: "Gold Ingot", stat: 0, ingredients: [{ qty: 6, item: "Gold Ore" }, { qty: 6, item: "Charcoal" }] },
  { station: "Smelter", category: "Ingots & Refined Materials", name: "Iron Ingot", stat: 0, ingredients: [{ qty: 6, item: "Iron Ore" }, { qty: 6, item: "Poor Charcoal" }] },
  { station: "Smelter", category: "Ingots & Refined Materials", name: "Orichalcum Ingot", stat: 0, ingredients: [{ qty: 6, item: "Orichalcum Ore" }, { qty: 6, item: "Charcoal Briquette" }] },
  { station: "Smelter", category: "Ingots & Refined Materials", name: "Quicksilver Ingot", stat: 0, ingredients: [{ qty: 6, item: "Quicksilver Ore" }, { qty: 6, item: "Coke" }] },
  { station: "Smelter", category: "Ingots & Refined Materials", name: "Refined Malachite", stat: 0, ingredients: [{ qty: 6, item: "Malachite Ore" }, { qty: 6, item: "Coke" }] },
  { station: "Smelter", category: "Ingots & Refined Materials", name: "Refined Moonstone", stat: 0, ingredients: [{ qty: 6, item: "Moonstone Ore" }, { qty: 6, item: "Charcoal Briquette" }] },
  { station: "Smelter", category: "Ingots & Refined Materials", name: "Silver Ingot", stat: 0, ingredients: [{ qty: 6, item: "Silver Ore" }, { qty: 6, item: "Charcoal" }] },
  { station: "Smelter", category: "Ingots & Refined Materials", name: "Steel Ingot", stat: 0, ingredients: [{ qty: 3, item: "Corundum Ore" }, { qty: 3, item: "Iron Ore" }, { qty: 6, item: "Charcoal" }] },
  { station: "Smelter", category: "Dwemer Scrap Melting", name: "Dwarven Metal Ingot \u2014 from Bent Dwemer Scrap Metal", stat: 0, ingredients: [{ qty: 1, item: "Bent Dwemer Scrap Metal" }] },
  { station: "Smelter", category: "Dwemer Scrap Melting", name: "Dwarven Metal Ingot \u2014 from Large Decorative Dwemer Strut", stat: 0, ingredients: [{ qty: 1, item: "Large Decorative Dwemer Strut" }] },
  { station: "Smelter", category: "Dwemer Scrap Melting", name: "Dwarven Metal Ingot \u2014 from Large Dwemer Plate Metal", stat: 0, ingredients: [{ qty: 1, item: "Large Dwemer Plate Metal" }] },
  { station: "Smelter", category: "Dwemer Scrap Melting", name: "Dwarven Metal Ingot \u2014 from Large Dwemer Strut", stat: 0, ingredients: [{ qty: 1, item: "Large Dwemer Strut" }] },
  { station: "Smelter", category: "Dwemer Scrap Melting", name: "Dwarven Metal Ingot \u2014 from Small Dwemer Plate Metal", stat: 0, ingredients: [{ qty: 1, item: "Small Dwemer Plate Metal" }] },
  { station: "Smelter", category: "Dwemer Scrap Melting", name: "Dwarven Metal Ingot \u2014 from Solid Dwemer Metal", stat: 0, ingredients: [{ qty: 1, item: "Solid Dwemer Metal" }] },
];

/** Weapons are rated by damage, everything else by armour. */
export const statLabel = (category: string) =>
  /weapon|ammo|arrow|bow/i.test(category) ? 'Damage' : 'Armor';

/** Stations in the order the doc lists them. */
export const STATIONS = [...new Set(RECIPES.map((r) => r.station))].filter(Boolean);
